Run java files with main class
Fix for this error:

/usercode/file.java:13: error: class Main is public, should be declared in a file named Main.java
public class Main {

And I don't thin there will be any breakings due to this but it helps for files with Main class